# SPDX-License-Identifier: MIT
"""
Deterministic MCP server generator.

Creates a minimal Model Context Protocol server repository using
pure template generation (no LLM usage).

Example output:

generated_mcp_github/
  README.md
  manifest.json
  server.py
  tools/
    list_repositories.py
    get_repository.py
    create_issue.py
  tests/
    test_server_import.py
"""

import argparse
import json
from pathlib import Path


def write(path: Path, content: str):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content.strip() + "\n", encoding="utf-8")


def build_manifest(name, capability, tools):
    return {
        "name": name,
        "capability": capability,
        "tools": tools,
        "protocol": "model-context-protocol",
        "version": "0.1.0"
    }


def generate_repo(name, capability, tools, output_dir):
    root = Path(output_dir)

    manifest = build_manifest(name, capability, tools)

    write(
        root / "README.md",
        f"""
# {name}

Experimental MCP server generated by the MCP Automation Factory.

Capability:
{capability}
"""
    )

    write(
        root / "manifest.json",
        json.dumps(manifest, indent=2, sort_keys=True)
    )

    write(
        root / "server.py",
        f"""
\"\"\"
Minimal MCP server stub.
\"\"\"

TOOLS = {tools}

def list_tools():
    return TOOLS
"""
    )

    for tool in tools:

        write(
            root / "tools" / f"{tool}.py",
            f"""
def {tool}():
    return {{"status": "ok", "tool": "{tool}"}}
"""
        )

    write(
        root / "tests" / "test_server_import.py",
        """
import server

def test_list_tools():
    tools = server.list_tools()
    assert isinstance(tools, list)
"""
    )


def main():
    parser = argparse.ArgumentParser(description="Generate a deterministic MCP server")

    parser.add_argument("--name", required=True)
    parser.add_argument("--capability", required=True)
    parser.add_argument("--tools", nargs="+", required=True)
    parser.add_argument("--output-dir", required=True)

    args = parser.parse_args()

    generate_repo(
        args.name,
        args.capability,
        args.tools,
        args.output_dir
    )


if __name__ == "__main__":
    main()
